name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.5'  # Use the appropriate Python version

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Zip Lambda function
        run: |
          zip -r my_lambda_function.zip .  # Zips the current directory contents

      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1" # Set your AWS region here
        run: |
          aws lambda update-function-code \
            --function-name "TestLambda2" \
            --zip-file fileb://my_lambda_function.zip
