name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Check out code
        uses: actions/checkout@v2

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # 3. Install dependencies and build TypeScript code
      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # This runs `tsc` to compile TypeScript

      # 4. Zip the compiled files
      - name: Zip the files
        run: zip -r function.zip dist

      # 5. Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      # 6. Deploy to AWS Lambda using AWS CLI
      - name: Deploy to AWS Lambda
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1" # Set your AWS region here
        run: |
          aws lambda update-function-code \
            --function-name "<Your Lambda Function Name>" \
            --zip-file fileb://function.zip
